### PR TITLE
Fix broken javascript link in scheduleviewer (markers do not show)

### LINKED ISSUE #417: Schedule Viewer fails to show stops (those with yellow markers and times)
Hello

I noticed recenlty that schedule viewer does not show stops (as a yellow marker + time with it) either when displaying a route shape (displays only shape instead of shape and yellow stop markers and time with it), or when searching for a stop_id (shows nothing at all). (Pic. 1)

Query returns no errors in command prompt window. (Pic. 2)

I've tried to check on different browsers, different machines and with different GTFS files.

image
Pic. 1

image
Pic. 2

### PR DESCRIPTION
**Pull request by bhelx**
Resolves  #417

The current route to the `markerwithlabel` plugin is 404ing and is breaking the scheduleviewer page. I decided to embed it since hotlinking was not such a good idea to begin with. It was hard to find a version of this file that worked. I ended up finding this here:
https://raw.githubusercontent.com/printercu/google-maps-utility-library-v3-read-only/master/markerwithlabel/src/markerwithlabel.js

### CODE REVIEW

**Comment by bhelx** [comment]
I signed it!

**Comment by barbeau** [comment]
Thanks @bhelx!  I believe this fixes https://github.com/google/transitfeed/issues/417, right?

**Comment by bhelx** [comment]
@barbeau correct. Sorry I didn't see that issue but this should close it. The result of this bug is that the markers do not show. I've amended the description to reference and auto-close the issue.

**Comment by barbeau** [comment]
@bhelx Thanks!

@RachM or @dbabramov - would you be able to review/merge this?  The Schedule Viewer tool is currently broken, and this should fix it (note that I haven't personally tested this patch, but others in https://github.com/google/transitfeed/issues/417 say this fixes the issue).

**Comment by bhelx** [comment]
@barbeau is this repo still maintained? Seems like it hasn't been touched since 2015.

**Comment by barbeau** [comment]
@bhelx Not sure :). I'm trying to figure out who still has commit permissions here and is involved in GTFS. I know Google had a major transition in their transit team so they are probably still figuring this out.  This is technically the official GTFS validator and I'd love to get some of the Best Practices (http://gtfs.org/best-practices/) integrated here too. 

There is also https://github.com/conveyal/gtfs-validator which we are actively contributing to and integrating as part of https://github.com/CUTR-at-USF/gtfs-realtime-validator.

**Comment by RachM** [comment]
Hi Sean,

I'd like to merge this, but unfortunately I don't have access. I'm working on it - hopefully it won't be too much longer.

Thanks for your patience,
Rachael

**Comment by barbeau** [comment]
Thanks Rachael!

On Mar 25, 2017 7:01 PM, "Rachael Morgan" <notifications@github.com> wrote:

Hi Sean,

I'd like to merge this, but unfortunately I don't have access. I'm working
on it - hopefully it won't be too much longer.

Thanks for your patience,
Rachael

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/google/transitfeed/pull/425#issuecomment-289245522>,
or mute
the thread

**Comment by barbeau** [comment]
I've tested this PR locally now, LGTM!

**Comment by RachM** [comment]
I have now have access, so I can merge!

**Comment by barbeau** [comment]
Yay! :+1: Thanks Rachael! :)

**Comment by bhelx** [comment]
Thanks @RachM and @barbeau. Glad there is a maintainer!

**Comment by RachM** [comment]
Apologies for the wait, but hopefully merges should happen quickly from now on :-)

**Pull request merged**
