### PR TITLE
python3 porting

### PR DESCRIPTION
**Pull request by pecalleja**
Python3 porting with all tests running ok.

### CODE REVIEW

**Comment by pecalleja** [comment]
@googlebot I signed it!

**Comment by jarondl** [comment]
This is one git commit with 99 files and git status of  `+29,726 −24,238`

I cannot review such a thing. I don't think anyone can read 60K lines of changes.

@avilaton and me started Python3 porting in smaller steps. If you can contribute small, reviewable changes, that would be welcome. Most auto-porting tools (which I assume you used), allow to apply only partial transformations, by choosing which transformers to apply.

**Comment by pecalleja** [comment]
@googlebot I consent.

**Comment by pecalleja** [comment]
Sorry for my mistake, I just wanted to help to make this port. How can I fix my mistake? Currently, all tests for Python 3.7 are already running. how can I go forward with the collaboration?

**Comment by pedrocalleja** [comment]
at least can we have a separate branch for python3 support ?

**Comment by pecalleja** [comment]
at least can we have a separate branch for python3 support ?

**Comment by jarondl** [comment]
How would we maintain that branch? Do you plan to submit every change to master to this branch too?
Let's update master to python3, but piece by piece. See #412

**Pull request closed without merging**
