### PR TITLE
[python3] small changes porting

### PR DESCRIPTION
**Pull request by pecalleja**
fix compatibility problems with python3 in small changes.

### CODE REVIEW

**Comment by markstos** [comment]
What's the status of getting the Python 3 port merged?

**Comment by markstos** [comment]
I noticed @pecalleja has a "python3" branch in his repo, but this pull request is against his "develop" branch:

https://github.com/pecalleja/transitfeed/compare/develop...pecalleja:python3

Does the `develop` branch have the most up-to-date that's proposed to be merged?

**Comment by pecalleja** [comment]
Hi @markstos, I've worked on two different approaches here...  the first was the `python3` branch in my forked repo https://github.com/pecalleja/transitfeed/tree/python3 . that PR was too big and was rejected https://github.com/google/transitfeed/pull/491 ,  so I started again from scratch the porting but with a new approach, avoiding auto-porting tools and making small changes in every commit fixing one tests at time.  my branch `develop` is my current working one and it is some commits behind the master version of the upstream repo.

**Comment by markstos** [comment]
@pecalleja Thanks for your effort. 

I see that your carefully crafted re-write of your pull request earned you a year of silence from the maintainers, as if continuing to support Python 2 code was a reasonable option.

**Comment by markstos** [comment]
Ah, it appears the whole project may be abandoned. The last release was two years ago and last commits were a year ago.  Time for someone to fork-and-release if there's interest.

**Comment by carlfredl** [comment]
👋  Indeed I don't think the Python project here is still active. We're working on a new, Canonical GTFS Validator here https://github.com/MobilityData/gtfs-validator.

**Comment by markstos** [comment]
@carlfredl Thanks for the link!

**Comment by pecalleja** [comment]
I'm out

**Pull request closed without merging**
